exclude: '^.*\.json'
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    -   id: clang-format
        'types_or': [c++, c, cuda]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        args:
            [
                "--skip-string-normalization",
            ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
