# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/d/Research/ML for Quantum/quartz"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/d/Research/ML for Quantum/quartz"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/lzk/cmake-3.21.3-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/Research/ML for Quantum/quartz/CMakeFiles" "/mnt/d/Research/ML for Quantum/quartz//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/d/Research/ML for Quantum/quartz/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named quartz_runtime

# Build rule for target.
quartz_runtime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quartz_runtime
.PHONY : quartz_runtime

# fast build rule for target.
quartz_runtime/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/build
.PHONY : quartz_runtime/fast

src/core/arb_complex.o: src/core/arb_complex.cpp.o
.PHONY : src/core/arb_complex.o

# target to build an object file
src/core/arb_complex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/arb_complex.cpp.o
.PHONY : src/core/arb_complex.cpp.o

src/core/arb_complex.i: src/core/arb_complex.cpp.i
.PHONY : src/core/arb_complex.i

# target to preprocess a source file
src/core/arb_complex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/arb_complex.cpp.i
.PHONY : src/core/arb_complex.cpp.i

src/core/arb_complex.s: src/core/arb_complex.cpp.s
.PHONY : src/core/arb_complex.s

# target to generate assembly for a file
src/core/arb_complex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/arb_complex.cpp.s
.PHONY : src/core/arb_complex.cpp.s

src/core/context.o: src/core/context.cpp.o
.PHONY : src/core/context.o

# target to build an object file
src/core/context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/context.cpp.o
.PHONY : src/core/context.cpp.o

src/core/context.i: src/core/context.cpp.i
.PHONY : src/core/context.i

# target to preprocess a source file
src/core/context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/context.cpp.i
.PHONY : src/core/context.cpp.i

src/core/context.s: src/core/context.cpp.s
.PHONY : src/core/context.s

# target to generate assembly for a file
src/core/context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/context.cpp.s
.PHONY : src/core/context.cpp.s

src/core/dag.o: src/core/dag.cpp.o
.PHONY : src/core/dag.o

# target to build an object file
src/core/dag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dag.cpp.o
.PHONY : src/core/dag.cpp.o

src/core/dag.i: src/core/dag.cpp.i
.PHONY : src/core/dag.i

# target to preprocess a source file
src/core/dag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dag.cpp.i
.PHONY : src/core/dag.cpp.i

src/core/dag.s: src/core/dag.cpp.s
.PHONY : src/core/dag.s

# target to generate assembly for a file
src/core/dag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dag.cpp.s
.PHONY : src/core/dag.cpp.s

src/core/dagnode.o: src/core/dagnode.cpp.o
.PHONY : src/core/dagnode.o

# target to build an object file
src/core/dagnode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dagnode.cpp.o
.PHONY : src/core/dagnode.cpp.o

src/core/dagnode.i: src/core/dagnode.cpp.i
.PHONY : src/core/dagnode.i

# target to preprocess a source file
src/core/dagnode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dagnode.cpp.i
.PHONY : src/core/dagnode.cpp.i

src/core/dagnode.s: src/core/dagnode.cpp.s
.PHONY : src/core/dagnode.s

# target to generate assembly for a file
src/core/dagnode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dagnode.cpp.s
.PHONY : src/core/dagnode.cpp.s

src/core/dataset.o: src/core/dataset.cpp.o
.PHONY : src/core/dataset.o

# target to build an object file
src/core/dataset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dataset.cpp.o
.PHONY : src/core/dataset.cpp.o

src/core/dataset.i: src/core/dataset.cpp.i
.PHONY : src/core/dataset.i

# target to preprocess a source file
src/core/dataset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dataset.cpp.i
.PHONY : src/core/dataset.cpp.i

src/core/dataset.s: src/core/dataset.cpp.s
.PHONY : src/core/dataset.s

# target to generate assembly for a file
src/core/dataset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/dataset.cpp.s
.PHONY : src/core/dataset.cpp.s

src/core/equivalence_set.o: src/core/equivalence_set.cpp.o
.PHONY : src/core/equivalence_set.o

# target to build an object file
src/core/equivalence_set.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/equivalence_set.cpp.o
.PHONY : src/core/equivalence_set.cpp.o

src/core/equivalence_set.i: src/core/equivalence_set.cpp.i
.PHONY : src/core/equivalence_set.i

# target to preprocess a source file
src/core/equivalence_set.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/equivalence_set.cpp.i
.PHONY : src/core/equivalence_set.cpp.i

src/core/equivalence_set.s: src/core/equivalence_set.cpp.s
.PHONY : src/core/equivalence_set.s

# target to generate assembly for a file
src/core/equivalence_set.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/equivalence_set.cpp.s
.PHONY : src/core/equivalence_set.cpp.s

src/core/gate.o: src/core/gate.cpp.o
.PHONY : src/core/gate.o

# target to build an object file
src/core/gate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/gate.cpp.o
.PHONY : src/core/gate.cpp.o

src/core/gate.i: src/core/gate.cpp.i
.PHONY : src/core/gate.i

# target to preprocess a source file
src/core/gate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/gate.cpp.i
.PHONY : src/core/gate.cpp.i

src/core/gate.s: src/core/gate.cpp.s
.PHONY : src/core/gate.s

# target to generate assembly for a file
src/core/gate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/gate.cpp.s
.PHONY : src/core/gate.cpp.s

src/core/gate_utils.o: src/core/gate_utils.cpp.o
.PHONY : src/core/gate_utils.o

# target to build an object file
src/core/gate_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/gate_utils.cpp.o
.PHONY : src/core/gate_utils.cpp.o

src/core/gate_utils.i: src/core/gate_utils.cpp.i
.PHONY : src/core/gate_utils.i

# target to preprocess a source file
src/core/gate_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/gate_utils.cpp.i
.PHONY : src/core/gate_utils.cpp.i

src/core/gate_utils.s: src/core/gate_utils.cpp.s
.PHONY : src/core/gate_utils.s

# target to generate assembly for a file
src/core/gate_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/gate_utils.cpp.s
.PHONY : src/core/gate_utils.cpp.s

src/core/generator.o: src/core/generator.cpp.o
.PHONY : src/core/generator.o

# target to build an object file
src/core/generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/generator.cpp.o
.PHONY : src/core/generator.cpp.o

src/core/generator.i: src/core/generator.cpp.i
.PHONY : src/core/generator.i

# target to preprocess a source file
src/core/generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/generator.cpp.i
.PHONY : src/core/generator.cpp.i

src/core/generator.s: src/core/generator.cpp.s
.PHONY : src/core/generator.s

# target to generate assembly for a file
src/core/generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/generator.cpp.s
.PHONY : src/core/generator.cpp.s

src/core/substitution.o: src/core/substitution.cpp.o
.PHONY : src/core/substitution.o

# target to build an object file
src/core/substitution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/substitution.cpp.o
.PHONY : src/core/substitution.cpp.o

src/core/substitution.i: src/core/substitution.cpp.i
.PHONY : src/core/substitution.i

# target to preprocess a source file
src/core/substitution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/substitution.cpp.i
.PHONY : src/core/substitution.cpp.i

src/core/substitution.s: src/core/substitution.cpp.s
.PHONY : src/core/substitution.s

# target to generate assembly for a file
src/core/substitution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/substitution.cpp.s
.PHONY : src/core/substitution.cpp.s

src/core/tasograph.o: src/core/tasograph.cpp.o
.PHONY : src/core/tasograph.o

# target to build an object file
src/core/tasograph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/tasograph.cpp.o
.PHONY : src/core/tasograph.cpp.o

src/core/tasograph.i: src/core/tasograph.cpp.i
.PHONY : src/core/tasograph.i

# target to preprocess a source file
src/core/tasograph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/tasograph.cpp.i
.PHONY : src/core/tasograph.cpp.i

src/core/tasograph.s: src/core/tasograph.cpp.s
.PHONY : src/core/tasograph.s

# target to generate assembly for a file
src/core/tasograph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/tasograph.cpp.s
.PHONY : src/core/tasograph.cpp.s

src/core/vector.o: src/core/vector.cpp.o
.PHONY : src/core/vector.o

# target to build an object file
src/core/vector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/vector.cpp.o
.PHONY : src/core/vector.cpp.o

src/core/vector.i: src/core/vector.cpp.i
.PHONY : src/core/vector.i

# target to preprocess a source file
src/core/vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/vector.cpp.i
.PHONY : src/core/vector.cpp.i

src/core/vector.s: src/core/vector.cpp.s
.PHONY : src/core/vector.s

# target to generate assembly for a file
src/core/vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/vector.cpp.s
.PHONY : src/core/vector.cpp.s

src/core/verifier.o: src/core/verifier.cpp.o
.PHONY : src/core/verifier.o

# target to build an object file
src/core/verifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/verifier.cpp.o
.PHONY : src/core/verifier.cpp.o

src/core/verifier.i: src/core/verifier.cpp.i
.PHONY : src/core/verifier.i

# target to preprocess a source file
src/core/verifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/verifier.cpp.i
.PHONY : src/core/verifier.cpp.i

src/core/verifier.s: src/core/verifier.cpp.s
.PHONY : src/core/verifier.s

# target to generate assembly for a file
src/core/verifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/quartz_runtime.dir/build.make CMakeFiles/quartz_runtime.dir/src/core/verifier.cpp.s
.PHONY : src/core/verifier.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... quartz_runtime"
	@echo "... src/core/arb_complex.o"
	@echo "... src/core/arb_complex.i"
	@echo "... src/core/arb_complex.s"
	@echo "... src/core/context.o"
	@echo "... src/core/context.i"
	@echo "... src/core/context.s"
	@echo "... src/core/dag.o"
	@echo "... src/core/dag.i"
	@echo "... src/core/dag.s"
	@echo "... src/core/dagnode.o"
	@echo "... src/core/dagnode.i"
	@echo "... src/core/dagnode.s"
	@echo "... src/core/dataset.o"
	@echo "... src/core/dataset.i"
	@echo "... src/core/dataset.s"
	@echo "... src/core/equivalence_set.o"
	@echo "... src/core/equivalence_set.i"
	@echo "... src/core/equivalence_set.s"
	@echo "... src/core/gate.o"
	@echo "... src/core/gate.i"
	@echo "... src/core/gate.s"
	@echo "... src/core/gate_utils.o"
	@echo "... src/core/gate_utils.i"
	@echo "... src/core/gate_utils.s"
	@echo "... src/core/generator.o"
	@echo "... src/core/generator.i"
	@echo "... src/core/generator.s"
	@echo "... src/core/substitution.o"
	@echo "... src/core/substitution.i"
	@echo "... src/core/substitution.s"
	@echo "... src/core/tasograph.o"
	@echo "... src/core/tasograph.i"
	@echo "... src/core/tasograph.s"
	@echo "... src/core/vector.o"
	@echo "... src/core/vector.i"
	@echo "... src/core/vector.s"
	@echo "... src/core/verifier.o"
	@echo "... src/core/verifier.i"
	@echo "... src/core/verifier.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

