./run_nam.sh ../Nam_1_1_complete_ECC_set.json > scalability_11.txt
./run_nam.sh ../Nam_2_1_complete_ECC_set.json > scalability_21.txt &
./run_nam.sh ../Nam_2_2_complete_ECC_set.json > scalability_22.txt &
./run_nam.sh ../Nam_2_3_complete_ECC_set.json > scalability_23.txt &
./run_nam.sh ../Nam_2_4_complete_ECC_set.json > scalability_24.txt &
./run_nam.sh ../Nam_3_1_complete_ECC_set.json > scalability_31.txt &
./run_nam.sh ../Nam_3_2_complete_ECC_set.json > scalability_32.txt &
./run_nam.sh ../Nam_3_3_complete_ECC_set.json > scalability_33.txt &
./run_nam.sh ../Nam_3_4_complete_ECC_set.json > scalability_34.txt &
./run_nam.sh ../Nam_4_1_complete_ECC_set.json > scalability_41.txt &
./run_nam.sh ../Nam_4_2_complete_ECC_set.json > scalability_42.txt &
./run_nam.sh ../Nam_4_3_complete_ECC_set.json > scalability_43.txt &
./run_nam.sh ../Nam_4_4_complete_ECC_set.json > scalability_44.txt &
./run_nam.sh ../Nam_5_1_complete_ECC_set.json > scalability_51.txt &
./run_nam.sh ../Nam_5_2_complete_ECC_set.json > scalability_52.txt &
./run_nam.sh ../Nam_5_3_complete_ECC_set.json > scalability_53.txt &
./run_nam.sh ../Nam_5_4_complete_ECC_set.json > scalability_54.txt &
./run_nam.sh ../Nam_6_1_complete_ECC_set.json > scalability_61.txt &
./run_nam.sh ../Nam_6_2_complete_ECC_set.json > scalability_62.txt &
./run_nam.sh ../Nam_6_3_complete_ECC_set.json > scalability_63.txt &
./run_nam.sh ../Nam_6_4_complete_ECC_set.json > scalability_64.txt &
./run_nam.sh ../Nam_7_1_complete_ECC_set.json > scalability_71.txt &
./run_nam.sh ../Nam_7_2_complete_ECC_set.json > scalability_72.txt &
./run_nam.sh ../Nam_7_3_complete_ECC_set.json > scalability_73.txt &
./run_nam.sh ../Nam_8_1_complete_ECC_set.json > scalability_81.txt &
./run_nam.sh ../Nam_8_2_complete_ECC_set.json > scalability_82.txt &
./run_nam.sh ../Nam_8_3_complete_ECC_set.json > scalability_83.txt &
