import math

import sympy
import z3

use_sympy = True

meta_index_num_qubits = 0
meta_index_num_gates = 1
# Only if generated by CircuitSeq::to_json(/*keep_hash_value=*/true),
# the following are present.
meta_index_other_hash_values = 2
meta_index_original_fingerprint = 3

kCheckPhaseShiftOfPiOver4Index = 10000  # A copy of the value in utils.h


# helper constants

sqrt2 = z3.Real("sqrt2")
sqrt3 = z3.Real("sqrt3")
sqrt5 = z3.Real("sqrt5")
sqrt_of_2_plus_sqrt2 = z3.Real("sqrt_of_2_plus_sqrt2")
sqrt_of_2_minus_sqrt2 = z3.Real("sqrt_of_2_minus_sqrt2")
sqrt_of_5_minus_sqrt5 = z3.Real("sqrt_of_5_minus_sqrt5")
kConstantEquations = [
    sqrt2 * sqrt2 == 2,
    sqrt3 * sqrt3 == 3,
    sqrt5 * sqrt5 == 5,
    sqrt_of_2_plus_sqrt2 * sqrt_of_2_plus_sqrt2 == 2 + sqrt2,
    sqrt_of_2_minus_sqrt2 * sqrt_of_2_minus_sqrt2 == 2 - sqrt2,
    sqrt_of_5_minus_sqrt5 * sqrt_of_5_minus_sqrt5 == 5 - sqrt5,
]
if use_sympy:
    sqrt2 = sympy.sqrt(2)
    sqrt3 = sympy.sqrt(3)
    sqrt5 = sympy.sqrt(5)
    sqrt_of_2_plus_sqrt2 = sympy.sqrt(2 + sqrt2)
    sqrt_of_2_minus_sqrt2 = sympy.sqrt(2 - sqrt2)
    sqrt_of_5_minus_sqrt5 = sympy.sqrt(5 - sqrt5)


kPhaseFactorCoeffs = [0, 1, -1, 2, -2]
kPhaseFactorConstant = math.pi / 8.0
kPhaseFactorConstantCoeffMin = 0
kPhaseFactorConstantCoeffMax = 15
kPhaseFactorConstantCosTable = [
    1,
    sqrt_of_2_plus_sqrt2 / 2,
    1.0 / sqrt2,
    sqrt_of_2_minus_sqrt2 / 2,
    0,
    -sqrt_of_2_minus_sqrt2 / 2,
    -1.0 / sqrt2,
    -sqrt_of_2_plus_sqrt2 / 2,
    -1,
    -sqrt_of_2_plus_sqrt2 / 2,
    -1.0 / sqrt2,
    -sqrt_of_2_minus_sqrt2 / 2,
    0,
    sqrt_of_2_minus_sqrt2 / 2,
    1.0 / sqrt2,
    sqrt_of_2_plus_sqrt2 / 2,
]
kPhaseFactorConstantSinTable = [
    0,
    sqrt_of_2_minus_sqrt2 / 2,
    1.0 / sqrt2,
    sqrt_of_2_plus_sqrt2 / 2,
    1,
    sqrt_of_2_plus_sqrt2 / 2,
    1.0 / sqrt2,
    sqrt_of_2_minus_sqrt2 / 2,
    0,
    -sqrt_of_2_minus_sqrt2 / 2,
    -1.0 / sqrt2,
    -sqrt_of_2_plus_sqrt2 / 2,
    -1,
    -sqrt_of_2_plus_sqrt2 / 2,
    -1.0 / sqrt2,
    -sqrt_of_2_minus_sqrt2 / 2,
]
kPhaseFactorEpsilon = 1e-6
