// A mapping from GateType to Gate subclasses.
PER_GATE(h, HGate)
PER_GATE(x, XGate)
PER_GATE(y, YGate)
PER_GATE(rx, RXGate)
PER_GATE(ry, RYGate)
PER_GATE(rz, RZGate)
PER_GATE(cx, CXGate)
PER_GATE(ccx, CCXGate)
PER_GATE(add, AddGate)
PER_GATE(z, ZGate)
PER_GATE(s, SGate)
PER_GATE(t, TGate)
PER_GATE(tdg, TDGGate)
PER_GATE(ch, CHGate)
PER_GATE(swap, SWAPGate)
