cd ../src/test

python test_t_tdg_rm.py adder_8 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py barenco_tof_3 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py barenco_tof_4 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py barenco_tof_5 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py barenco_tof_10 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py csla_mux_3 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py csum_mux_9 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^4_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^5_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^6_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^7_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^8_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^9_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^10_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^16_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py gf2^32_mult ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py mod5_4 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py mod_mult_55 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py mod_red_21 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py qcla_adder_10 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py qcla_com_7 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py qcla_mod_7 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py rc_adder_6 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py tof_3 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py tof_4 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py tof_5 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py tof_10 ../../t_tdg_rm_output & sleep 10
python test_t_tdg_rm.py vbe_adder_3 ../../t_tdg_rm_output & sleep 10
